<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<TargetFramework>net8.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Serilog" Version="4.4.0" />
		<PackageReference Include="Serilog.Sinks.Console" Version="6.1.1" />
		<PackageReference Include="Serilog.Sinks.Seq" Version="9.1.0" />

		<!-- Читання конфігурації під .NET 8 (ніяких 10-к!) -->
		<PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="8.0.0" />
		<PackageReference Include="Serilog.Settings.Configuration" Version="8.0.4" />

		<!-- Аналізатори -->
		<PackageReference Include="Roslynator.Analyzers" Version="4.12.9" />
		<PackageReference Include="StyleCop.Analyzers" Version="1.2.0-beta.556" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\SoftwareEngineering.BLL\SoftwareEngineering.BLL.csproj" />
	</ItemGroup>

	<ItemGroup>
		<None Update="appsettings.json">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
	</ItemGroup>

</Project>
